apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot-ms-gcp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot-ms-gcp
    spec:
      containers:
        - name: springboot-ms-gcp
          image: gct.io/govindacloud09072019/springboot-ms-gcp
          ports:
            - containerPort: 8080