apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot-rest-gcp
spec:
  replicas: 4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: springboot-rest-gcp
    spec:
      containers:
        - name: springboot-rest-gcp
          image: gcr.io/govindacloud09072019/springboot-rest-gcp
          ports:
            - containerPort: 8080