apiVersion: v1
kind: Service
metadata:
  name: springboot-rest-gcp
  labels:
    name: springboot-rest-gcp
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: springboot-rest-gcp
  type: LoadBalancer