apiVersion: v1
kind: Service
metadata:
  name: springboot-ms-gcp-service
  labels:
    name: springboot-ms-gcp-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: springboot-ms-gcp
  type: LoadBalancer